# syntax=docker/docker-compose:1
services:
  bot:
    restart: always
    build:
      context: .
      args:
        # 環境変数をビルド時の引数に渡す
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    volumes:
      - ./:/app
    working_dir: "/app"
    tty: true
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - app-join-left-bot-net
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - app-join-left-bot-net

networks:
  app-join-left-bot-net:
    driver: bridge

volumes:
  db-data: